create table public.users
(
    user_id             bigint generated by default as identity
        primary key,
    user_account_number varchar(255) not null
        constraint uk80n2fr6itj1wm4iv11s1sncbq
            unique,
    user_email          varchar(255),
    user_name           varchar(255) not null,
    phone_number        varchar(255)
);

alter table public.users
    owner to dasun;

