create table public.bill_item
(
    id              bigint generated by default as identity
        primary key,
    priceatpurchase integer not null,
    quantity        integer not null,
    bill_id         bigint
        constraint fkgys7iqbf1ibalojc1dcgcf6if
            references public.bills,
    item_id         bigint
        constraint fk7ke829j0nmedplxv3uyj9ggo9
            references public.items
);

alter table public.bill_item
    owner to dasun;

