create table public.bills
(
    bill_id     bigint generated by default as identity
        primary key,
    bill_amount integer not null,
    bill_date   date    not null,
    user_id     bigint
        constraint fkk8vs7ac9xknv5xp18pdiehpp1
            references public.users
);

alter table public.bills
    owner to dasun;

