create table public.items
(
    item_id    bigint generated by default as identity
        primary key,
    item_name  varchar(255) not null,
    item_price integer      not null,
    item_stock integer      not null
);

alter table public.items
    owner to dasun;

